# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

source_set("pubky_update") {
  sources = [
    "controller.cc",
    "controller.h",
  ]
  public_deps = [
    "//base",
    "//chrome/common/pubky_update:buildflags",
    "//chrome/common/pubky_update:record",
    "//services/network/public/cpp",
  ]
  deps = [
    "//components/prefs",
    "//net",
  ]
  if (is_mac) {
    sources += [
      "mac_adapter.h",
      "mac_adapter.mm",
      "mac_feed_policy.cc",
      "mac_feed_policy.h",
    ]
    deps += [ "//third_party/sparkle" ]
  }
  if (is_win) {
    sources += [
      "windows_adapter.cc",
      "windows_adapter.h",
    ]
    deps += [
      "//base/version_info",
      "//chrome/browser/lifetime",
      "//chrome/browser/lifetime:termination_notification",
      "//chrome/install_static:install_static_util",
      "//chrome/installer/pubky_update:lib",
      "//chrome/installer/util:with_no_strings",
      "//crypto",
    ]
  }
}

source_set("unit_tests") {
  testonly = true
  sources = [ "controller_unittest.cc" ]
  deps = [
    ":pubky_update",
    "//base",
    "//base/test:test_support",
    "//chrome/common/pubky_update:record",
    "//chrome/common/pubky_update:test_support",
    "//components/prefs:test_support",
    "//crypto",
    "//net",
    "//services/network:test_support",
    "//testing/gtest",
  ]
  if (is_mac) {
    sources += [ "mac_feed_policy_unittest.cc" ]
  }
  if (is_win) {
    sources += [ "windows_adapter_unittest.cc" ]
    deps += [
      "//chrome/installer/pubky_update:lib",
      "//chrome/installer/util:with_no_strings",
    ]
  }
}
