#!/bin/sh
#
# Copyright 2009 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e

action="$1"

# Only do complete clean-up on purge.
if [ "$action" != "purge" ] ; then
  exit 0
fi

@@include@@../common/variables.include

@@include@@../common/symlinks.include

remove_udev_symlinks

# Pubky Chromium: postinst creates no /etc/default file, apt source or
# keyring, so purge leaves those paths alone. Their names are shared with
# other chromium-browser packages, and removing them here would delete
# another installation's configuration.
